apiVersion: v1
kind: Pod
metadata:
  name: postgres-app-pod
  labels:
    name: postgres-app
    app: demo-voting-app
spec:
  containers:
   - name: postgres-app
     image: postgres-app-image
   - ports:
     - containerPort: 5432
     env:
     - name: POSTGRES_USER
       value: "postgres"
     - name: POSTGRES_PASSWORD
       value: "postgres"    
   