apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-app-pod
  labels:
    name: voting-app
    app: demo-voting-app
spec:
  template:
   metadata:
    name: redis-app-pod
    labels:
     name: redis-app
     app: demo-voting-app
   spec:
    containers:
    - name: redis
      image: redis
    - ports:
      - containerPort: 6379
  selector:
    matchLabels:
       name: voting-app
       app: demo-voting-app
  replicas: 1
