apiVersion: v1
kind: Pod
metadata:
  name: redis-app-pod
  labels:
    name: redis-app
    app: demo-voting-app
spec:
  containers:
   - name: redis-app
     image: redis-app-image
   - ports:
     - containerPort: 6379
   