apiVersion: v1
kind: Pod
metadata:
  name: result-app-pod
  labels:
    name: result-app
    app: demo-voting-app
spec:
  containers:
   - name: result-app
     image: result-app-image
   - ports:
     - containerPort: 80